version: '3'

services:
  app:
    image: go-rt-dev:1.22
    container_name: lab-leilao
    restart: no
    ports:
      - 8088:8080
    volumes:
      - /Users/rogeriotadim/git-projects/github/rogeriotadim/pos-goexpert/lab-leilao/src:/app
    networks:
      - lab-leilao

  db:
    image: mongo
    container_name: mongo-db
    restart: no
    ports:
      - 27017
    networks:
      - lab-leilao

networks:
  lab-leilao:
    driver: bridge
