version: '3'

services:
  app:
    image: go-rt-dev:1.22
    container_name: lab-leilao
    restart: no
    ports:
      - 8088:8080
    volumes:
      - /Users/rogeriotadim/git-projects/github/rogeriotadim/pos-goexpert/lab-leilao/src:/app
    networks:
      - lab-leilao
networks:
  lab-leilao:
    driver: bridge
